# generated by datamodel-codegen:
#   filename:  plugin-manifest.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Manifest(BaseModel):
    engine_id: Annotated[str, Field(description='引擎标识，如 rpgmv')]
    display_name: Annotated[str, Field(description='展示名，如 RPG Maker MV/MZ')]
    api_version: Annotated[str, Field(description='插件 API 版本契约，不匹配拒绝加载')]
    version: Annotated[str, Field(description='插件版本（semver，独立于主程序）')]
    entry: Annotated[str, Field(description='适配器入口文件名，如 adapter.py')]
    author: str | None = None
