/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 条目状态机（M1）：1=PENDING 2=MACHINE 3=EDITED 4=CONFIRMED。一键重翻不得覆盖 CONFIRMED。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "EntryStatus".
 */
export type EntryStatus = 1 | 2 | 3 | 4;
/**
 * 项目生命周期（M1 pipeline.py）：Created→Detecting→Extracted→Translating⇄Reviewing→WritingBack→Done。非法迁移抛异常。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProjectState".
 */
export type ProjectState =
  "created" | "detecting" | "extracted" | "translating" | "reviewing" | "writing_back" | "done";

export interface HttpsGametrDevSchemasCommonJson {
  [k: string]: unknown;
}
/**
 * detect.run 返回值：引擎识别 + 置信度（M2）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "DetectResult".
 */
export interface DetectResult {
  /**
   * 引擎标识，如 rpgmv
   */
  engine_id: string;
  /**
   * 展示名，如 RPG Maker MV/MZ
   */
  display_name: string;
  /**
   * 探测到的引擎版本
   */
  version?: string;
  /**
   * 0..1 置信度
   */
  confidence: number;
  /**
   * 插件自定义附加信息
   */
  details?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * 长任务每批完成发一条 progress 通知（M3）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProgressEvent".
 */
export interface ProgressEvent {
  task_id: string;
  /**
   * extract / translate / write_back
   */
  phase: string;
  done: number;
  total: number;
  message?: string;
  [k: string]: unknown;
}
/**
 * M0 健康检查：GUI 启动时 500ms 间隔重试直到成功。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "PingResult".
 */
export interface PingResult {
  pong: true;
  /**
   * 核心版本
   */
  version: string;
  /**
   * sidecar 进程号
   */
  pid: number;
  /**
   * 服务器时间戳（秒）
   */
  ts: number;
  [k: string]: unknown;
}
/**
 * M1 IR 数据模型。locator 不透明（ADR-0003），核心只存不解析。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "Entry".
 */
export interface Entry {
  /**
   * 稳定 ID：sha1(engine_id + locator标准化 + source前256字符)[:16]
   */
  id: string;
  source: string;
  translation?: string | null;
  status: EntryStatus;
  /**
   * 不透明定位串，插件负责生成与解析
   */
  locator: string;
  /**
   * 上下文元信息 JSON 串
   */
  context_json?: string | null;
  /**
   * 警告列表 JSON 串
   */
  warnings_json?: string | null;
  /**
   * 更新时间戳（秒）
   */
  updated_at: number;
  [k: string]: unknown;
}
/**
 * JSON-RPC error 对象（-32700..-32000，错误码表见 rpc-methods.json）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "RpcError".
 */
export interface RpcError {
  code: number;
  message: string;
  /**
   * 可选附加数据
   */
  data?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
