/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 条目状态机（M1）：1=PENDING 2=MACHINE 3=EDITED 4=CONFIRMED。一键重翻不得覆盖 CONFIRMED。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "EntryStatus".
 */
export type EntryStatus = 1 | 2 | 3 | 4;
/**
 * 项目生命周期（M1 pipeline.py）：Created→Detecting→Extracted→Translating⇄Reviewing→WritingBack→Done。非法迁移抛异常。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProjectState".
 */
export type ProjectState =
  "created" | "detecting" | "extracted" | "translating" | "reviewing" | "writing_back" | "done";
/**
 * 翻译任务生命周期（M3，任务表细粒度，不进项目状态机）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "TranslateStatus".
 */
export type TranslateStatus = "running" | "paused" | "cancelled" | "done" | "error";

export interface HttpsGametrDevSchemasCommonJson {
  [k: string]: unknown;
}
/**
 * detect.run 返回值：引擎识别 + 置信度（M2）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "DetectResult".
 */
export interface DetectResult {
  /**
   * 引擎标识，如 rpgmv
   */
  engine_id: string;
  /**
   * 展示名，如 RPG Maker MV/MZ
   */
  display_name: string;
  /**
   * 探测到的引擎版本
   */
  version?: string;
  /**
   * 0..1 置信度
   */
  confidence: number;
  /**
   * 插件自定义附加信息
   */
  details?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * 长任务进度通知（M3 起服务端推送，JSON-RPC 通知无 id）。progress 一个方法覆盖全部任务生命周期（看 status 区分）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProgressEvent".
 */
export interface ProgressEvent {
  task_id: string;
  /**
   * extract / translate / write_back
   */
  phase: string;
  done: number;
  total: number;
  message?: string | null;
  /**
   * 事件时间戳（秒）
   */
  ts?: number;
  /**
   * 任务生命周期：running/paused/cancelled/done/error（终态也要发一条）
   */
  status?: "running" | "paused" | "cancelled" | "done" | "error";
  /**
   * 续翻/缓存命中已跳过的条数（前端进度条从非零起步）
   */
  skipped?: number;
  [k: string]: unknown;
}
/**
 * M0 健康检查：GUI 启动时 500ms 间隔重试直到成功。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "PingResult".
 */
export interface PingResult {
  pong: true;
  /**
   * 核心版本
   */
  version: string;
  /**
   * sidecar 进程号
   */
  pid: number;
  /**
   * 服务器时间戳（秒）
   */
  ts: number;
  [k: string]: unknown;
}
/**
 * M1 IR 数据模型。locator 不透明（ADR-0003），核心只存不解析。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "Entry".
 */
export interface Entry {
  /**
   * 稳定 ID：sha1(engine_id + locator标准化 + source前256字符)[:16]
   */
  id: string;
  source: string;
  translation?: string | null;
  status: EntryStatus;
  /**
   * 人工修改标记（M4）：1=曾被人工编辑（与 status 正交——机翻条目改后 status 仍 2 但 edited=1，可同时被机翻与已修改筛选命中）
   */
  edited?: number;
  /**
   * 最近一次 AI 机翻输出（基线，M4）：人工编辑只改 translation，machine_text 保留 AI 原文——机翻·已改条目可查看/恢复机翻内容。纯机翻未改时等于 translation；从未机翻过为 null
   */
  machine_text?: string | null;
  /**
   * 不透明定位串，插件负责生成与解析
   */
  locator: string;
  /**
   * 上下文元信息 JSON 串
   */
  context_json?: string | null;
  /**
   * 警告列表 JSON 串
   */
  warnings_json?: string | null;
  /**
   * 更新时间戳（秒）
   */
  updated_at: number;
  [k: string]: unknown;
}
/**
 * JSON-RPC error 对象（-32700..-32000，错误码表见 rpc-methods.json）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "RpcError".
 */
export interface RpcError {
  code: number;
  message: string;
  /**
   * 可选附加数据
   */
  data?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * 术语表条目（M1）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "GlossaryEntry".
 */
export interface GlossaryEntry {
  id: number;
  term: string;
  translation: string;
  /**
   * 是否区分大小写匹配
   */
  match_case?: boolean;
  [k: string]: unknown;
}
/**
 * 通用分页结果（M1）：items 为 Entry[]。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "Page".
 */
export interface Page {
  items: Entry[];
  page: number;
  page_size: number;
  total: number;
  [k: string]: unknown;
}
/**
 * project.create / project.open 返回值（M1）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProjectInfo".
 */
export interface ProjectInfo {
  path: string;
  engine_id: string;
  source_path: string;
  project_state: ProjectState;
  /**
   * 项目文件 schema 版本（meta 表记录）
   */
  schema_version: number;
  /**
   * 创建时间戳（秒）
   */
  created_at: number;
  [k: string]: unknown;
}
/**
 * project.stats 返回值：条目总数 + 状态分布（M1）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProjectStats".
 */
export interface ProjectStats {
  total: number;
  /**
   * status int -> 计数
   */
  by_status: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
/**
 * extract.run 返回值（M2，M1 定义类型）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ExtractResult".
 */
export interface ExtractResult {
  engine_id: string;
  extracted_count: number;
  duration_ms: number;
  message?: string;
  [k: string]: unknown;
}
/**
 * write_back 返回值（M2，M1 定义类型）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "WriteBackResult".
 */
export interface WriteBackResult {
  output_dir: string;
  written_count: number;
  warning_count: number;
  message?: string;
  [k: string]: unknown;
}
/**
 * plugins.list 返回值：已加载插件信息（含 disabled 状态与失败原因，M2）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "PluginInfo".
 */
export interface PluginInfo {
  /**
   * 引擎标识，如 rpgmv
   */
  engine_id: string;
  /**
   * 展示名，如 RPG Maker MV/MZ
   */
  display_name: string;
  /**
   * 插件版本（semver）
   */
  version: string;
  /**
   * 插件 API 版本契约
   */
  api_version: string;
  /**
   * 适配器入口文件名，如 adapter.py
   */
  entry: string;
  /**
   * 是否加载成功并可用（契约测试通过）
   */
  loaded: boolean;
  /**
   * 加载失败原因；loaded=false 时有值
   */
  error?: string | null;
  /**
   * 插件可选能力列表（feature-detect）：如 protect=占位符保护器
   */
  features?: string[];
  [k: string]: unknown;
}
/**
 * 翻译任务状态（translate.start/status 返回值，M3）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "TranslateTask".
 */
export interface TranslateTask {
  task_id: string;
  status: TranslateStatus;
  provider_id: string;
  model: string;
  /**
   * 风格预设 ID（null=默认风格）
   */
  style_id?: string | null;
  /**
   * 任务启动时的术语表内容哈希（参与 cache_key）
   */
  glossary_version?: string;
  total: number;
  done: number;
  error?: string | null;
  created_at: number;
  updated_at: number;
  [k: string]: unknown;
}
/**
 * 翻译用量统计（translate.stats 返回值，M4 成本面板）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "TranslateStats".
 */
export interface TranslateStats {
  task_id: string;
  provider_id: string;
  model: string;
  tokens_in: number;
  tokens_out: number;
  estimated_cost: number;
  currency?: string;
  [k: string]: unknown;
}
/**
 * providers.list 返回值：Provider 选择器渲染所需（M3）。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProviderInfo".
 */
export interface ProviderInfo {
  provider_id: string;
  display_name: string;
  /**
   * 可用模型列表（模型下拉框）
   */
  models: string[];
  /**
   * 是否需要密钥（MockProvider=false，前端据此显示密钥输入框）
   */
  needs_api_key: boolean;
  /**
   * 是否支持 response_format json_schema strict
   */
  supports_structured: boolean;
  /**
   * OpenAI 兼容端点 base_url（可配置项）
   */
  base_url?: string;
  [k: string]: unknown;
}
/**
 * providers.test 返回值：连通性自检。
 *
 * This interface was referenced by `HttpsGametrDevSchemasCommonJson`'s JSON-Schema
 * via the `definition` "ProviderTestResult".
 */
export interface ProviderTestResult {
  provider_id: string;
  ok: boolean;
  latency_ms?: number;
  message?: string | null;
  [k: string]: unknown;
}
