/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 引擎插件清单（M2 插件框架）。api_version 不匹配则拒绝加载并在 RPC 报错。
 */
export interface Manifest {
  /**
   * 引擎标识，如 rpgmv
   */
  engine_id: string;
  /**
   * 展示名，如 RPG Maker MV/MZ
   */
  display_name: string;
  /**
   * 插件 API 版本契约，不匹配拒绝加载
   */
  api_version: string;
  /**
   * 插件版本（semver，独立于主程序）
   */
  version: string;
  /**
   * 适配器入口文件名，如 adapter.py
   */
  entry: string;
  author?: string;
  [k: string]: unknown;
}
