# generated by datamodel-codegen:
#   filename:  common.json

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel




class EntryStatus(IntEnum):
    PENDING = 1
    MACHINE = 2
    EDITED = 3
    CONFIRMED = 4


class ProjectState(StrEnum):
    created = 'created'
    detecting = 'detecting'
    extracted = 'extracted'
    translating = 'translating'
    reviewing = 'reviewing'
    writing_back = 'writing_back'
    done = 'done'


class DetectResult(BaseModel):
    engine_id: Annotated[str, Field(description='引擎标识，如 rpgmv')]
    display_name: Annotated[str, Field(description='展示名，如 RPG Maker MV/MZ')]
    version: Annotated[str | None, Field(description='探测到的引擎版本')] = None
    confidence: Annotated[float, Field(description='0..1 置信度', ge=0.0, le=1.0)]
    details: Annotated[
        dict[str, Any] | None, Field(description='插件自定义附加信息')
    ] = None


class Status(StrEnum):
    running = 'running'
    paused = 'paused'
    cancelled = 'cancelled'
    done = 'done'
    error = 'error'


class ProgressEvent(BaseModel):
    task_id: str
    phase: Annotated[str, Field(description='extract / translate / write_back')]
    done: int
    total: int
    message: str | None = None
    ts: Annotated[float | None, Field(description='事件时间戳（秒）')] = None
    status: Annotated[
        Status | None,
        Field(
            description='任务生命周期：running/paused/cancelled/done/error（终态也要发一条）'
        ),
    ] = None
    skipped: Annotated[
        int | None,
        Field(description='续翻/缓存命中已跳过的条数（前端进度条从非零起步）'),
    ] = None


class PingResult(BaseModel):
    pong: Literal[True]
    version: Annotated[str, Field(description='核心版本')]
    pid: Annotated[int, Field(description='sidecar 进程号')]
    ts: Annotated[float, Field(description='服务器时间戳（秒）')]


class Entry(BaseModel):
    id: Annotated[
        str,
        Field(
            description='稳定 ID：sha1(engine_id + locator标准化 + source前256字符)[:16]'
        ),
    ]
    source: str
    translation: str | None = None
    status: EntryStatus
    edited: Annotated[
        int | None,
        Field(
            description='人工修改标记（M4）：1=曾被人工编辑（与 status 正交——机翻条目改后 status 仍 2 但 edited=1，可同时被机翻与已修改筛选命中）'
        ),
    ] = 0
    machine_text: Annotated[
        str | None,
        Field(
            description='最近一次 AI 机翻输出（基线，M4）：人工编辑只改 translation，machine_text 保留 AI 原文——机翻·已改条目可查看/恢复机翻内容。纯机翻未改时等于 translation；从未机翻过为 null'
        ),
    ] = None
    locator: Annotated[str, Field(description='不透明定位串，插件负责生成与解析')]
    context_json: Annotated[str | None, Field(description='上下文元信息 JSON 串')] = (
        None
    )
    warnings_json: Annotated[str | None, Field(description='警告列表 JSON 串')] = None
    updated_at: Annotated[float, Field(description='更新时间戳（秒）')]


class RpcError(BaseModel):
    code: int
    message: str
    data: Annotated[Any | None, Field(description='可选附加数据')] = None


class GlossaryEntry(BaseModel):
    id: int
    term: str
    translation: str
    match_case: Annotated[bool | None, Field(description='是否区分大小写匹配')] = None


class Page(BaseModel):
    items: list[Entry]
    page: int
    page_size: int
    total: int


class ProjectInfo(BaseModel):
    path: str
    engine_id: str
    source_path: str
    project_state: ProjectState
    schema_version: Annotated[
        int, Field(description='项目文件 schema 版本（meta 表记录）')
    ]
    created_at: Annotated[float, Field(description='创建时间戳（秒）')]


class ProjectStats(BaseModel):
    total: int
    by_status: Annotated[dict[str, int], Field(description='status int -> 计数')]


class ExtractResult(BaseModel):
    engine_id: str
    extracted_count: int
    duration_ms: float
    message: str | None = None


class WriteBackResult(BaseModel):
    output_dir: str
    written_count: int
    warning_count: int
    message: str | None = None


class PluginInfo(BaseModel):
    engine_id: Annotated[str, Field(description='引擎标识，如 rpgmv')]
    display_name: Annotated[str, Field(description='展示名，如 RPG Maker MV/MZ')]
    version: Annotated[str, Field(description='插件版本（semver）')]
    api_version: Annotated[str, Field(description='插件 API 版本契约')]
    entry: Annotated[str, Field(description='适配器入口文件名，如 adapter.py')]
    loaded: Annotated[bool, Field(description='是否加载成功并可用（契约测试通过）')]
    error: Annotated[
        str | None, Field(description='加载失败原因；loaded=false 时有值')
    ] = None
    features: Annotated[
        list[str] | None,
        Field(
            description='插件可选能力列表（feature-detect）：如 protect=占位符保护器'
        ),
    ] = None


class TranslateStatus(StrEnum):
    running = 'running'
    paused = 'paused'
    cancelled = 'cancelled'
    done = 'done'
    error = 'error'


class TranslateTask(BaseModel):
    task_id: str
    status: TranslateStatus
    provider_id: str
    model: str
    style_id: Annotated[
        str | None, Field(description='风格预设 ID（null=默认风格）')
    ] = None
    glossary_version: Annotated[
        str | None, Field(description='任务启动时的术语表内容哈希（参与 cache_key）')
    ] = None
    total: int
    done: int
    error: str | None = None
    created_at: float
    updated_at: float


class TranslateStats(BaseModel):
    task_id: str
    provider_id: str
    model: str
    tokens_in: int
    tokens_out: int
    estimated_cost: float
    currency: str | None = None


class ProviderInfo(BaseModel):
    provider_id: str
    display_name: str
    models: Annotated[list[str], Field(description='可用模型列表（模型下拉框）')]
    needs_api_key: Annotated[
        bool,
        Field(description='是否需要密钥（MockProvider=false，前端据此显示密钥输入框）'),
    ]
    supports_structured: Annotated[
        bool, Field(description='是否支持 response_format json_schema strict')
    ]
    base_url: Annotated[
        str | None, Field(description='OpenAI 兼容端点 base_url（可配置项）')
    ] = None


class ProviderTestResult(BaseModel):
    provider_id: str
    ok: bool
    latency_ms: float | None = None
    message: str | None = None
