# generated by datamodel-codegen:
#   filename:  common.json

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel




class EntryStatus(IntEnum):
    PENDING = 1
    MACHINE = 2
    EDITED = 3
    CONFIRMED = 4


class ProjectState(StrEnum):
    created = 'created'
    detecting = 'detecting'
    extracted = 'extracted'
    translating = 'translating'
    reviewing = 'reviewing'
    writing_back = 'writing_back'
    done = 'done'


class DetectResult(BaseModel):
    engine_id: Annotated[str, Field(description='引擎标识，如 rpgmv')]
    display_name: Annotated[str, Field(description='展示名，如 RPG Maker MV/MZ')]
    version: Annotated[str | None, Field(description='探测到的引擎版本')] = None
    confidence: Annotated[float, Field(description='0..1 置信度', ge=0.0, le=1.0)]
    details: Annotated[
        dict[str, Any] | None, Field(description='插件自定义附加信息')
    ] = None


class ProgressEvent(BaseModel):
    task_id: str
    phase: Annotated[str, Field(description='extract / translate / write_back')]
    done: int
    total: int
    message: str | None = None


class PingResult(BaseModel):
    pong: Literal[True]
    version: Annotated[str, Field(description='核心版本')]
    pid: Annotated[int, Field(description='sidecar 进程号')]
    ts: Annotated[float, Field(description='服务器时间戳（秒）')]


class Entry(BaseModel):
    id: Annotated[
        str,
        Field(
            description='稳定 ID：sha1(engine_id + locator标准化 + source前256字符)[:16]'
        ),
    ]
    source: str
    translation: str | None = None
    status: EntryStatus
    locator: Annotated[str, Field(description='不透明定位串，插件负责生成与解析')]
    context_json: Annotated[str | None, Field(description='上下文元信息 JSON 串')] = (
        None
    )
    warnings_json: Annotated[str | None, Field(description='警告列表 JSON 串')] = None
    updated_at: Annotated[float, Field(description='更新时间戳（秒）')]


class RpcError(BaseModel):
    code: int
    message: str
    data: Annotated[Any | None, Field(description='可选附加数据')] = None


class GlossaryEntry(BaseModel):
    id: int
    term: str
    translation: str
    match_case: Annotated[bool | None, Field(description='是否区分大小写匹配')] = None


class Page(BaseModel):
    items: list[Entry]
    page: int
    page_size: int
    total: int


class ProjectInfo(BaseModel):
    path: str
    engine_id: str
    source_path: str
    project_state: ProjectState
    schema_version: Annotated[
        int, Field(description='项目文件 schema 版本（meta 表记录）')
    ]
    created_at: Annotated[float, Field(description='创建时间戳（秒）')]


class ProjectStats(BaseModel):
    total: int
    by_status: Annotated[dict[str, int], Field(description='status int -> 计数')]


class ExtractResult(BaseModel):
    engine_id: str
    extracted_count: int
    duration_ms: float
    message: str | None = None


class WriteBackResult(BaseModel):
    output_dir: str
    written_count: int
    warning_count: int
    message: str | None = None
